[build]
target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc]
linker = "D:\\Environment\\VSBuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\Hostx64\\x64\\link.exe"

[env]
CARGO_INCREMENTAL = "0"
VCToolsInstallDir = "D:\\Environment\\VSBuildTools\\VC\\Tools\\MSVC\\14.44.35207\\"
WindowsSdkDir = "C:\\Program Files (x86)\\Windows Kits\\10\\"
WindowsSDKVersion = "10.0.26100.0\\"
LIB = "D:\\Environment\\VSBuildTools\\VC\\Tools\\MSVC\\14.44.35207\\lib\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.26100.0\\ucrt\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.26100.0\\um\\x64"
INCLUDE = "D:\\Environment\\VSBuildTools\\VC\\Tools\\MSVC\\14.44.35207\\include;D:\\Environment\\VSBuildTools\\VC\\Auxiliary\\VS\\include;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.26100.0\\ucrt;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.26100.0\\um;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.26100.0\\shared;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.26100.0\\winrt;C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.26100.0\\cppwinrt"
